---
- name: {{ appname }} app setup
  hosts: app_prod
  become: yes
  roles:
    - role: deploy
      tags: app

- name: {{ appname }} database setup
  hosts: db_prod
  become: yes
  roles:
    - role: db_setup
      tags: db

- name: {{ appname }} Redis setup
  hosts: redis_prod
  become: yes
  roles:
    - role: redis_setup
      tags: redis

